import 'dart:convert';

import 'package:http/http.dart' as http;

import '../config.dart';

class ApiClient {
  final http.Client _client = http.Client();

  /// Fetches the stored summary for a call (generated by the backend from
  /// persisted transcripts — the recovery path for calls ended abruptly).
  /// Allow a long timeout: the backend generates it on-demand with a slow
  /// free-tier LLM (measured ~60s).
  Future<Map<String, dynamic>> fetchSummary(String roomId) async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/sessions/$roomId/summary');
    final res = await _client.get(uri).timeout(const Duration(seconds: 120));
    if (res.statusCode != 200) {
      String detail = 'summary request failed (${res.statusCode})';
      try {
        final body = jsonDecode(res.body) as Map<String, dynamic>;
        if (body['detail'] != null) detail = body['detail'] as String;
      } catch (_) {}
      throw Exception(detail);
    }
    return jsonDecode(res.body) as Map<String, dynamic>;
  }

  /// Creates a patient record for the signed-in user (best-effort demo path —
  /// failures are swallowed by the caller).
  Future<Map<String, dynamic>> createPatient({
    required String name,
    String age = '',
    String sex = '',
    String knownConditions = '',
    String allergies = '',
    String ownerId = '',
  }) async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/patients');
    final res = await _client
        .post(
          uri,
          headers: {'Content-Type': 'application/json'},
          body: jsonEncode({
            'name': name,
            'age': age,
            'sex': sex,
            'known_conditions': knownConditions,
            'allergies': allergies,
            'owner_id': ownerId,
          }),
        )
        .timeout(const Duration(seconds: 30));
    if (res.statusCode < 200 || res.statusCode >= 300) {
      throw Exception(_detail(res, 'patient creation failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as Map<String, dynamic>;
  }

  /// Lists all patients stored by the backend.
  Future<List<dynamic>> fetchPatients() async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/patients');
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      throw Exception(_detail(res, 'patients request failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as List<dynamic>;
  }

  /// Lists available appointment slots as
  /// `{"slots": [{"datetime": "...", "label": "Tomorrow 09:00"}, ...]}`.
  Future<List<dynamic>> fetchSlots() async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/slots');
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      throw Exception(_detail(res, 'slots request failed (${res.statusCode})'));
    }
    return (jsonDecode(res.body) as Map<String, dynamic>)['slots'] as List;
  }

  /// Books an appointment for the given slot label; returns the created
  /// booking (id, patient_id, room_id, name, slot, reason, status, created_at).
  Future<Map<String, dynamic>> createBooking({
    required String slot,
    String roomId = '',
    String patientId = '',
    String name = '',
    String reason = '',
  }) async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/bookings');
    final res = await _client
        .post(
          uri,
          headers: {'Content-Type': 'application/json'},
          body: jsonEncode({
            'patient_id': patientId,
            'room_id': roomId,
            'name': name,
            'slot': slot,
            'reason': reason,
          }),
        )
        .timeout(const Duration(seconds: 30));
    if (res.statusCode < 200 || res.statusCode >= 300) {
      throw Exception(_detail(res, 'booking failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as Map<String, dynamic>;
  }

  /// Lists call sessions for a user (or all when signed out), newest first.
  Future<List<dynamic>> fetchSessions({String ownerId = ''}) async {
    var uri = Uri.parse('${AppConfig.apiBaseUrl}/sessions');
    if (ownerId.isNotEmpty) {
      uri = uri.replace(queryParameters: {'owner_id': ownerId});
    }
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      throw Exception(_detail(res, 'sessions request failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as List<dynamic>;
  }

  /// Lists the transcript lines of a session (`{role, text, language, created_at}`).
  Future<List<dynamic>> fetchTranscripts(String roomId) async {
    final uri =
        Uri.parse('${AppConfig.apiBaseUrl}/sessions/$roomId/transcripts');
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      throw Exception(
          _detail(res, 'transcripts request failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as List<dynamic>;
  }

  /// Lists the bookings for a session.
  Future<List<dynamic>> fetchBookings(String roomId) async {
    final uri = Uri.parse(
        '${AppConfig.apiBaseUrl}/bookings?room_id=${Uri.encodeQueryComponent(roomId)}');
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      throw Exception(
          _detail(res, 'bookings request failed (${res.statusCode})'));
    }
    return jsonDecode(res.body) as List<dynamic>;
  }

  String _detail(http.Response res, String fallback) {
    try {
      final body = jsonDecode(res.body) as Map<String, dynamic>;
      if (body['detail'] != null) return body['detail'] as String;
    } catch (_) {}
    return fallback;
  }
}
