import 'dart:convert';

import 'package:http/http.dart' as http;

import '../config.dart';

class ApiClient {
  final http.Client _client = http.Client();

  /// Fetches the stored summary for a call (generated by the backend from
  /// persisted transcripts — the recovery path for calls ended abruptly).
  Future<Map<String, dynamic>> fetchSummary(String roomId) async {
    final uri = Uri.parse('${AppConfig.apiBaseUrl}/sessions/$roomId/summary');
    final res = await _client.get(uri).timeout(const Duration(seconds: 30));
    if (res.statusCode != 200) {
      String detail = 'summary request failed (${res.statusCode})';
      try {
        final body = jsonDecode(res.body) as Map<String, dynamic>;
        if (body['detail'] != null) detail = body['detail'] as String;
      } catch (_) {}
      throw Exception(detail);
    }
    return jsonDecode(res.body) as Map<String, dynamic>;
  }
}
