import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

/// Formats summary text and generates shareable PDF for the post-call care card.
class CareCardService {
  /// Formats a triage summary as human-readable plain text.
  static String formatSummaryText(Map<String, dynamic> summary) {
    final lines = <String>[
      '=== ClinicGuard Triage Summary ===',
      '',
      'Patient: ${summary['patient_name'] ?? 'Unknown'}',
      'Chief Complaint: ${summary['chief_complaint'] ?? ''}',
      'Urgency: ${(summary['urgency_level'] ?? 'low').toString().toUpperCase()}',
      '',
    ];

    final symptoms = summary['symptoms'];
    if (symptoms is List && symptoms.isNotEmpty) {
      lines.add('Symptoms:');
      for (final s in symptoms) {
        if (s is Map) {
          lines.add('  - ${s['symptom']} (severity: ${s['severity'] ?? 'N/A'}, onset: ${s['onset'] ?? 'N/A'})');
        } else {
          lines.add('  - $s');
        }
      }
      lines.add('');
    }

    final vitals = summary['vitals'];
    if (vitals is Map && vitals.isNotEmpty) {
      lines.add('Vitals:');
      for (final e in vitals.entries) {
        lines.add('  ${e.key}: ${e.value}');
      }
      lines.add('');
    }

    final raw = summary['recommended_actions'];
    final actions = raw is List
        ? raw.cast<String>()
        : (summary['recommendation'] != null
            ? [(summary['recommendation']!).toString()]
            : <String>[]);
    if (actions.isNotEmpty) {
      lines.add('Recommended Care Steps:');
      for (final a in actions) {
        lines.add('  -> $a');
      }
      lines.add('');
    }

    lines.addAll([
      '---',
      'Generated by ClinicGuard AI Triage Assistant',
      'This is not medical advice. Consult a healthcare professional.',
    ]);
    return lines.join('\n');
  }

  /// Generates a one-page PDF of the triage summary.
  static Future<Uint8List> buildSummaryPdf(Map<String, dynamic> summary) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.nunitoRegular();
    final fontBold = await PdfGoogleFonts.nunitoBold();

    final urgency = (summary['urgency_level'] ?? 'low').toString();
    final urgencyColor = switch (urgency) {
      'emergency' => PdfColors.red,
      'high' => PdfColors.orange,
      'medium' => PdfColors.amber,
      _ => PdfColors.green,
    };

    final rawActions = summary['recommended_actions'];
    final actions = rawActions is List
        ? rawActions.cast<String>()
        : (summary['recommendation'] != null
            ? [(summary['recommendation']!).toString()]
            : <String>[]);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => pw.Padding(
          padding: const pw.EdgeInsets.all(24),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('ClinicGuard Triage Summary',
                  style: pw.TextStyle(font: fontBold, fontSize: 20)),
              pw.SizedBox(height: 4),
              pw.Text(
                'Generated ${DateTime.now().toString().substring(0, 16)}',
                style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey),
              ),
              pw.Divider(),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: pw.BoxDecoration(
                  color: urgencyColor,
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  urgency.toUpperCase(),
                  style: pw.TextStyle(font: fontBold, fontSize: 12, color: PdfColors.white),
                ),
              ),
              pw.SizedBox(height: 12),
              _section('Patient', summary['patient_name'] ?? 'Unknown', fontBold, font),
              _section('Chief Complaint', summary['chief_complaint'] ?? '', fontBold, font),
              if (actions.isNotEmpty) ...[
                pw.SizedBox(height: 8),
                pw.Text('Recommended Care Steps:',
                    style: pw.TextStyle(font: fontBold, fontSize: 11)),
                for (final a in actions)
                  pw.Bullet(text: a, style: pw.TextStyle(font: font, fontSize: 10)),
              ],
              pw.Divider(),
              pw.SizedBox(height: 8),
              pw.Text(
                'This summary was generated by an AI triage assistant and does not '
                'constitute medical advice. Please consult a healthcare professional.',
                style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey),
              ),
            ],
          ),
        ),
      ),
    );
    return pdf.save();
  }

  static pw.Widget _section(String label, String value, pw.Font bold, pw.Font regular) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('$label: ', style: pw.TextStyle(font: bold, fontSize: 11)),
          pw.Expanded(
            child: pw.Text(value, style: pw.TextStyle(font: regular, fontSize: 11)),
          ),
        ],
      ),
    );
  }

  /// Shares the summary as plain text via the system share sheet.
  static Future<void> shareText(Map<String, dynamic> summary) async {
    final text = formatSummaryText(summary);
    await Share.share(text, subject: 'ClinicGuard Triage Summary');
  }

  /// Generates PDF and shares it via the system share sheet.
  static Future<void> sharePdf(Map<String, dynamic> summary) async {
    final bytes = await buildSummaryPdf(summary);
    await Printing.sharePdf(bytes: bytes, filename: 'clinicguard-care-card.pdf');
  }
}
